FROM ubuntu:18.04
MAINTAINER "jingq"<guoqun.jin@hotmail.com>
COPY sources.list /etc/apt/sources.list
RUN apt-get clean && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
        locales \
        git \
        python3 \
        python3-dev \
        python3-setuptools \
        python3-pip \
        nano \
        nginx \
        tesseract-ocr && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    pip3 install --upgrade setuptools pip -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple uwsgi==2.0.18 && \
    mkdir /opt/onlineocr
ENV TZ=Asia/Shanghai
RUN set -eux; \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime; \
    echo $TZ > /etc/timezone
ENV LANG en_US.utf8
ENV PYTHONUNBUFFERED 1
ENV PYTHONIOENCODING UTF-8
COPY requirements.txt /opt/onlineocr/
WORKDIR /opt/onlineocr
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY nginx.conf /etc/nginx/sites-available/default
EXPOSE 80